In [1]:
import numpy as np

import torch

li = np.array([[1, 2], [3, 4]])

#넘파이배열을 텐서로 변환

tensor1 = torch.tensor(li)

tensor2 = torch.as_tensor(li)

tensor3 = torch.from_numpy(li)

print(tensor1)

print(tensor2)

print(tensor3)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [2]:
#텐서를 넘파이배열로 변환

print(tensor1.numpy())

print(tensor2.numpy())

print(tensor3.numpy())

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [3]:
torch.manual_seed(0) #랜덤시드 고정

a = torch.rand(5) # 0 ~ 1 사이의 5개의 난수

b = torch.randn(5) # 평균 0, 표준편차 1인 5개의 난수

c = torch.randint(10, size=(5,)) # 0~9 사이의 5개의 난수

print(a)

print(b)

print(c)

tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074])
tensor([ 0.5507,  0.2704,  0.6472,  0.2490, -0.3354])
tensor([8, 4, 3, 6, 9])


In [4]:
print(torch.arange(1, 10)) # 1~9

print(torch.ones((2, 5))) # 2행 5열, 1로 채움

print(torch.zeros((3, 5))) #3행 5열, 0으로 채움

print(torch.linspace(0, 10, 5)) # 0~10, 5등분

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [5]:
#텐서의 형상 변환(reshape)

t1 = torch.ones(4, 3)

t2 = t1.view(3, 4) #3행 4열로 변환

t3 = t1.view(12) #1차원 배열로 변환

print(t1)

print(t2)

print(t3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [6]:
t1.view(1, 3, 4) #3차원으로 변환

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])